# Generated by Django 3.2 on 2022-08-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photo_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='category',
            new_name='categories',
        ),
    ]
