# Generated by Django 3.2 on 2022-08-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='decriptions',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
