# Generated by Django 3.2 on 2022-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_photo_decriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='decriptions',
        ),
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
