# Generated by Django 3.2 on 2022-08-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20220815_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
