# Generated by Django 3.2 on 2022-06-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(blank=True, default='DEFAULT VALUE', max_length=254, null=True)),
                ('message', models.CharField(max_length=1500, null=True)),
            ],
        ),
    ]
