# Generated by Django 3.2 on 2022-08-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='body',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
