# Generated by Django 3.2 on 2022-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_introduction_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='head',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='body',
            field=models.TextField(blank=True, max_length=2550, null=True),
        ),
    ]
