# Generated by Django 3.2 on 2022-08-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220803_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='placeholder', upload_to='', verbose_name='image'),
        ),
    ]
