# Generated by Django 3.2 on 2022-07-18 10:49

from django.db import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
